import { County } from "./CountyType";
export const Counties: County[] = [
  { county: "Bucuresti", id: "1" },
  { county: "Alba", id: "2" },
  { county: "Arad", id: "3" },
  { county: "Arges", id: "4" },
  { county: "Bacau", id: "5" },
  { county: "Bihor", id: "6" },
  { county: "Bistrita - Nasaud", id: "7" },
  { county: "Botosani", id: "8" },
  { county: "Braila", id: "9" },
  { county: "Brasov", id: "10" },
  { county: "Buzau", id: "11" },
  { county: "Calarasi", id: "12" },
  { county: " Caras - Severin", id: "13" },
  { county: "Cluj", id: "14" },
  { county: "Constanta", id: "15" },
  { county: "Covasna", id: "16" },
  { county: "Dambovita", id: "17" },
  { county: "Dolj", id: "18" },
  { county: "Galati", id: "19" },
  { county: "Giurgiu", id: "20" },
  { county: "Gorj", id: "21" },
  { county: "Harghita", id: "22" },
  { county: "Hunedoara", id: "23" },
  { county: "Ialomita", id: "24" },
  { county: "Iasi", id: "25" },
  { county: "Ilfov", id: "26" },
  { county: "Maramures", id: "27" },
  { county: "Mehedinti", id: "28" },
  { county: "Mures", id: "29" },
  { county: "Neamt", id: "30" },
  { county: "Olt", id: "31" },
  { county: "Prahova", id: "32" },
  { county: "Salaj", id: "33" },
  { county: "Satu Mare", id: "34" },
  { county: "Sibiu", id: "35" },
  { county: "Suceava", id: "36" },
  { county: "Teleorman", id: "37" },
  { county: "Timis", id: "38" },
  { county: "Tulcea", id: "39" },
  { county: "Valcea", id: "40" },
  { county: "Vaslui", id: "41" },
  { county: "Vrancea", id: "42" },
];
