import { GraduationCap } from "../type";

export const Products: GraduationCap[] = [
  {
    id: 1,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/1.jpg",
  },
  {
    id: 2,
    productname: "gr2",
    price: "100lei",
    productImage: "assets/images/2.jpg",
  },
  {
    id: 3,
    productname: "gr3",
    price: "100lei",
    productImage: "assets/images/3.jpg",
  },
  {
    id: 4,
    productname: "gr4",
    price: "100lei",
    productImage: "assets/images/4.jpg",
  },
  {
    id: 5,
    productname: "gr5",
    price: "100lei",
    productImage: "assets/images/5.jpg",
  },
  {
    id: 6,
    productname: "gr6",
    price: "100lei",
    productImage: "assets/images/6.jpg",
  },
  {
    id: 7,
    productname: "gr7",
    price: "100lei",
    productImage: "assets/images/7.jpg",
  },
  {
    id: 8,
    productname: "gr8",
    price: "100lei",
    productImage: "assets/images/8.jpg",
  },
  {
    id: 9,
    productname: "gr9",
    price: "100lei",
    productImage: "assets/images/9.jpg",
  },
  {
    id: 10,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/10.jpg",
  },
  {
    id: 11,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/11.JPG",
  },
  {
    id: 12,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/12.jpg",
  },
  {
    id: 13,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/13.jpg",
  },
  {
    id: 14,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/14.jpg",
  },
  {
    id: 15,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/15.jpg",
  },
  {
    id: 16,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/16.jpg",
  },
  {
    id: 17,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/17.jpg",
  },
  {
    id: 18,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/18.jpg",
  },
  {
    id: 19,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/19.jpg",
  },
  {
    id: 20,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/20.jpg",
  },
  {
    id: 21,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/21.jpg",
  },
  {
    id: 22,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/22.jpg",
  },
  {
    id: 23,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/23.jpg",
  },
  {
    id: 24,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/24.jpg",
  },
  {
    id: 25,
    productname: "gr1",
    price: "100lei",
    productImage: "assets/images/25.jpg",
  },
];
