import { GraduationCap } from "../type";

export const Products: GraduationCap[] = [
  {
    id: "1",
    productname: "Green leaves",
    price: 100,
    productImage: "assets/images/1.jpg",
  },
  {
    id: "2",
    productname: "Pharmacy1",
    price: 100,
    productImage: "assets/images/2.jpg",
  },
  {
    id: "3",
    productname: "Sunflowers",
    price: 100,
    productImage: "assets/images/3.jpg",
  },

  {
    id: " 5",
    productname: "Pink butterfly",
    price: 100,
    productImage: "assets/images/5.jpg",
  },
  {
    id: " 6",
    productname: "Chemistry2",
    price: 100,
    productImage: "assets/images/6.jpg",
  },
  {
    id: "7",
    productname: "Chemistry3",
    price: 100,
    productImage: "assets/images/7.jpg",
  },
  {
    id: "8",
    productname: "Chemistry4",
    price: 100,
    productImage: "assets/images/8.jpg",
  },
  {
    id: "9",
    productname: "Chemistry5",
    price: 100,
    productImage: "assets/images/9.jpg",
  },
  {
    id: "10",
    productname: "Chemistry6",
    price: 100,
    productImage: "assets/images/10.jpg",
  },
  {
    id: "11",
    productname: "White flowers",
    price: 100,
    productImage: "assets/images/11.JPG",
  },
  {
    id: "12",
    productname: "Chemistry7",
    price: 100,
    productImage: "assets/images/12.jpg",
  },
  {
    id: "13",
    productname: "Colorful structures",
    price: 100,
    productImage: "assets/images/13.jpg",
  },
  {
    id: "14",
    productname: "Chemistry8",
    price: 100,
    productImage: "assets/images/14.jpg",
  },
  {
    id: "15",
    productname: "Chemistry9",
    price: 100,
    productImage: "assets/images/15.jpg",
  },
  {
    id: "16",
    productname: "Chemistry10",
    price: 100,
    productImage: "assets/images/16.jpg",
  },
  {
    id: "17",
    productname: "White flower 2",
    price: 100,
    productImage: "assets/images/17.jpg",
  },
  {
    id: "18",
    productname: "Structures with flowers",
    price: 100,
    productImage: "assets/images/18.jpg",
  },
  {
    id: "19",
    productname: "Savage howl",
    price: 100,
    productImage: "assets/images/19.jpg",
  },
  {
    id: "20",
    productname: "Bloomed sthethoscope",
    price: 100,
    productImage: "assets/images/20.jpg",
  },
  {
    id: " 21",
    productname: "Roses are red",
    price: 100,
    productImage: "assets/images/21.jpg",
  },
  {
    id: "22",
    productname: "Golden hour",
    price: 100,
    productImage: "assets/images/22.jpg",
  },
  {
    id: "23",
    productname: "Panic at the disco",
    price: 100,
    productImage: "assets/images/23.jpg",
  },
  {
    id: "24",
    productname: "Bloomed cap",
    price: 100,
    productImage: "assets/images/24.jpg",
  },
  {
    id: "25",
    productname: "Machine",
    price: 100,
    productImage: "assets/images/25.jpg",
  },
  {
    id: "26",
    productname: "Melancholic crown",
    price: 100,
    productImage: "assets/images/26.jpg",
  },
  {
    id: " 27",
    productname: "Dis how i survived",
    price: 100,
    productImage: "assets/images/27.jpg",
  },
  {
    id: "28",
    productname: "Chemistry11",
    price: 100,
    productImage: "assets/images/28.jpg",
  },
  {
    id: "29",
    productname: "Colorful structures2",
    price: 100,
    productImage: "assets/images/29.jpg",
  },
  {
    id: "30",
    productname: "White flowers",
    price: 100,
    productImage: "assets/images/30.jpg",
  },
  {
    id: "31",
    productname: "Jack Sparrow and cacty",
    price: 100,
    productImage: "assets/images/31.jpg",
  },
  {
    id: "32",
    productname: "Dealer power puffs",
    price: 100,
    productImage: "assets/images/32.jpg",
  },
];
